name: Run Abola Scraper with Selenium

on:
  schedule:
    - cron: '*/2 * * * *'  # Executa a cada hora (UTC)
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
    - name: Clonar o repositório
      uses: actions/checkout@v3

    - name: Instalar Chrome
      run: |
        sudo apt-get update
        sudo apt-get install -y wget unzip xvfb
        wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
        sudo apt install -y ./google-chrome-stable_current_amd64.deb

    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Instalar dependências
      run: |
        pip install -r requirements.txt

    - name: Executar o script com Selenium + Xvfb
      run: |
        xvfb-run python abola_scrapper.py

    - name: Guardar os resultados
      uses: actions/upload-artifact@v4
      with:
        name: resultados-json
        path: abola_*.json
